baseURL = 'https://www.mindpatch.net/'
languageCode = 'en-us'
title = '@MindPatch'
# theme = 'hello-friend-ng' # Disabled - using custom minimalist theme

# Asset configuration
relativeURLs = false
canonifyURLs = false

# Suppress raw HTML warning
ignoreLogs = ['warning-goldmark-raw-html']

# Markdown configuration for Mermaid support
[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    codeFences = false
    guessSyntax = false
    lineNos = false
[pagination]
  pagerSize = 5

[params]
  dateform        = "Jan 2, 2006"
  dateformShort   = "Jan 2"
  dateformNum     = "2006-01-02"
  dateformNumTime = "2006-01-02 15:04"
  
  description = "Hi, I'm Khaled, a cybersecurity engineer passionate about offensive security, software development, and DevSecOps. I specialize in penetration testing, bug bounty hunting, vulnerability research, and security automation. Through my blog, I share practical security knowledge, CTF writeups, tool development insights, and challenge walkthroughs to help the cybersecurity community learn and grow. When I'm not breaking things, I'm building security tools in Rust and Python, contributing to open source projects, and mentoring aspiring security professionals."
  author = 'Khaled Nassar'
  keywords = ['cybersecurity', 'penetration testing', 'bug bounty', 'security research', 'vulnerability assessment', 'ethical hacking', 'security automation', 'CTF competitions', 'offensive security', 'mindpatch']
  images = ['/og-image.png']
  
  homeSubtitle = "Hi, I'm Khaled (MindPatch) - Offensive Security Engineer | Software Engineer | DevSecOps"
  enableSharingButtons = true
  enableGlobalLanguageMenu = false
  
[params.logo]
  logoMark = ">"
  logoText = "@MindPatch"
  logoHomeLink = "/"

[taxonomies]
  tag = "tags"
  category = "categories"

[[params.social]]
  name = "twitter"
  url = "https://twitter.com/mindpatchsec"

[[params.social]]
  name = "github"
  url = "https://github.com/mindpatch"

[[params.social]]
  name = "linkedin"
  url = "https://www.linkedin.com/in/knassar702/"

[params.opengraph]
  enable = true

[params.twitter_cards]
  enable = true
  creator = '@mindpatchsec'

[menu]
  [[menu.main]]
    name = "About"
    url = "/about"
    weight = 10

  [[menu.main]]
    name = "Blog"
    url = "/posts"
    weight = 15

  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 20
